export const projectsData = [
  {
    id: 1,
    title: "Chat App",
    description: "Project 1 description",
    image: "/images/projects/chat.jpg",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://mern-chat-gamma.vercel.app/",
  },
    {
      id: 2,
      title: "Weather Website",
      description: "Project 1 description",
      image: "/images/projects/weather.png",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://faizyi.github.io/react-weather-app/",
    },
    {
      id: 3,
      title: "Todo Website",
      description: "Project 2 description",
      image: "/images/projects/todo.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://faizyi.github.io/react-todoapp/",
    },
    {
      id: 4,
      title: "Expense Manager",
      description: "Project 3 description",
      image: "/images/projects/ems.png",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://faizyi.github.io/React-EMS/",
    },
  ];