export const projectsData = [
  {
    id: 1,
    title: "E-Commerce",
    shortDescription: "A modern e-commerce platform built with MERN stack.",
    description: "This project includes features like product listing, shopping cart, and secure checkout built using MongoDB, Express, React, and Node.js.",
    image: "/images/projects/e-commerce-1.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/faizyi/SAK-Shop-Ecommerce",
    previewUrl: "https://sak-shop-ecommerce.vercel.app/",
  },
  {
    id: 2,
    title: "Chat App",
    shortDescription: "Real-time chat application with messaging functionality using the MERN stack.",
    description: "I developed a real-time chat application using the MERN (MongoDB, Express, React, Node.js) stack and Socket.io, providing seamless one-on-one messaging functionality.",
    image: "/images/projects/chat.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/faizyi/MERN-Chat",
    previewUrl: "https://mern-chat-gamma.vercel.app/",
  },
  {
    id: 3,
    title: "Weather Website",
    shortDescription: "Weather forecasting website built with React.",
    description: "This project provides real-time weather information using the OpenWeatherMap API. It allows users to check the weather in any location by entering the city name.",
    image: "/images/projects/weather.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/faizyi/react-weather-app",
    previewUrl: "https://faizyi.github.io/react-weather-app/",
  },
  {
    id: 4,
    title: "Todo Website",
    shortDescription: "A simple todo list web application built with React.",
    description: "A simple and interactive todo list application that lets users add, edit, and delete tasks. This project is built using React.js and local storage for data persistence.",
    image: "/images/projects/todo.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/faizyi/react-todoapp",
    previewUrl: "https://faizyi.github.io/react-todoapp/",
  },
  {
    id: 5,
    title: "Expense Manager",
    shortDescription: "Track and manage your expenses with this expense manager app.",
    description: "This project allows users to add, edit, and delete expenses. It also helps users visualize their expenses through dynamic charts, built using React and Chart.js.",
    image: "/images/projects/ems.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/faizyi/React-EMS",
    previewUrl: "https://faizyi.github.io/React-EMS/",
  },
];
