import Education from "@/components/aboutSection/education/education";
import Skills from "@/components/aboutSection/skills/skills";
import ContactSection from "@/components/contactSection/ContactSection";
import HeroOne from "@/components/heroOne";
import HeroTwo from "@/components/heroTwo";
import ProjectsSection from "@/components/projectSection/ProjectsSection";

export const metadata = {
  title: "Faiz Noor",
  description: "Generated by create next app",
}

const Home = () => {
  return (
    <section className="lg:py-16 py-8 mt-20 sm:mt-20 md:mt-17 lg:mt-15">
      <div className="gap-8">
       <HeroOne/>
       <HeroTwo/>
       <ProjectsSection/>
       <Skills/>
       <Education/>
       <ContactSection/>
      </div>
    </section>
  );
};

export default Home;
